name: flutter_ffmpeg
description: Flutter plugin to run FFmpeg in the mobile platform. Supports iOS and Android.
version: 0.2.1
author: Taner Sener <tanersener@gmail.com>
homepage: https://github.com/tanersener/flutter-ffmpeg

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  path_provider: ^0.5.0+1
  path: ^1.6.2

flutter:
  plugin:
    androidPackage: com.arthenica.flutter.ffmpeg
    pluginClass: FlutterFFmpegPlugin